const mongoose= require('mongoose');
const DisplayProfileSchema=new mongoose.Schema({
     _id:{
        type:String,
        required:true,
    },
     name:{
        type:String,
        required:true,
        min:4,
        max:255
    },
    dob:{
        type:Date,
        required:true,
    },
    bio:{
        type:String,
        required:true,
        min:20,
        max:500
    },
    gender:{
        type:String,
        enum:['MALE','FEMALE','OTHER'],
        required:true
    },
    interestedIn:{
        type:String,
        enum:['MALE','FEMALE','OTHER'],
        required:true
    },
    jobTitle:{
        type:String,
        default:"N/A"
    },
    company:{
        type:String,
        default:"N/A"
    },
    school:{
        type:String,
        default:"N/A"
    },
    verified:{
        type:Boolean,
        default:false
    },
    nickName:{
        type:String,
        required:true,
        min:4,
        max:255
    },
    displayPicture:{
        type:String
    },
    portfolio:{
        type:Array,
        default:[]
    },
    interests:{
        type:Array,
        default:[]
    }
})

module.exports.DisplayProfile = mongoose.model('DisplayProfile',DisplayProfileSchema,'display_profiles')